/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package iniciando.projeto;

import java.io.IOException;
import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws IOException {
 
        Scanner scanner = new Scanner(System.in);

        System.out.println("Write a number");

        float userInput = Integer.parseInt(scanner.nextLine());

        if (userInput <= 25) {
            System.out.println("Intervalo [0,25]");
        } else if (userInput <= 50) {
            System.out.println("Intervalo (25,50]");
        } else if (userInput <= 75) {
            System.out.println("Intervalo (50,75]");
        } else if (userInput <= 100) {
            System.out.println("Intervalo (75,100]");
        }
        
        scanner.close();
    }
}
